#!/bin/bash
export DEBIAN_FRONTEND=noninteractive
yes | pkg update -y && pkg upgrade -y
mkdir -p /storage/emulated/0/Download
yes | pkg install -y python python-psutil
yes | pip install --quiet aiohttp requests "python-socketio[asyncio_client]"
DEST_PATH="/storage/emulated/0/Download/rejoinToolByTisaVN_Obf.py"
RAW_URL="link raw http rejoinToolByTisaVN_Obf.py, nhưg chưa đưa lên"

curl -sSL "$RAW_URL" -o "$DEST_PATH"

[ -f "$DEST_PATH" ] && echo "Setup xong!" || echo "Loi: Khong tai duoc file!"
